This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file D:/master-project/master-thesis/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (58 entries accepted, 0 rejected).
Sorting entries....done (338 comparisons).
Generating output file main.acr....done (60 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
